name: build

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: "Create required directories"
      run: |
        mkdir -p latex-beamer/build/text
    - name: Compile LaTeX document
      uses: fiedl/latex-action@master
      with:
        root_file: talk.tex
        working_directory: latex-beamer
        args: "--output-directory=build -pdf -file-line-error -interaction=nonstopmode -shell-escape"
        extra_packages: "cm-super"
    - name: Copy PDF output
      run: |
        mkdir public
        cp latex-beamer/build/*.pdf public/
    - name: Convert PDF to PNG for slide previews
      run: |
        cd public
        find . -type f -name '*.pdf' -print0 |
          while IFS= read -r -d '' file
            do convert -verbose -density 500 -resize 800 "${file}" "${file%.*}.png"
          done
    - name: GitHub Pages Deploy
      uses: maxheld83/ghpages@v0.2.1
      env:
        BUILD_DIR: public/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
