name: build

on: 
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@master
      with:
        root_file: talk.tex
        working_directory: latex-beamer
        args: "--output-directory=build -pdf -file-line-error -interaction=nonstopmode"
